blogTitle = "Geeked Out Solutions"
domain = "https://blog.geekedoutsolutions.com"
linkPrefix = "/"

noProductionJavascript = true

favicon = "/favicon.ico"
tagLine = "A blog about <a href='/tags/software/?tagline'>software development</a>, <a href='/tags/chatbots/?tagline'>chatbots</a>, and <a href='/tags/datacenter/?tagline'>datacenter automation</a>"
domainCDN = "https://static.sinap.ps"

authorShortName = "Brian"
authorName = "Brian Hopkins"
authorEmail = "btotharye@gmail.com"
authorTwitter = "@btotharye"
authorURL = "https://geekedoutsolutions.com"
authorImage = "https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/17021485_769502396781_4224567951634142620_n.jpg?oh=eba5642847cbc9695ddfd8b78848e0b6&oe=5B14920C"
authorIcon = "https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/17021485_769502396781_4224567951634142620_n.jpg?oh=eba5642847cbc9695ddfd8b78848e0b6&oe=5B14920C"
authorBlurb = "Hi, I'm <a href=''><strong>Brian</strong></a>.  More information about me to go here... '"
